results_path: str
wire_list_path: str
unused_pins_path: str
ground_path: str

continuity: true
isolation: true
hipot: true

continuity_cfg: 
  block_name: CONTINUITY_TESTS
  param: none
isolation_cfg:
  block_name: ISOLATION_TESTS
  param: none
hipot_cfg:
  block_name: HIPOT_TESTS
  param: none